### ISSUE TITLE
About code

### ISSUE THREAD

**Issue by milkcat0904** [RameenAbdal/StyleFlow#1]
hello, really interesting your work, I am trying to implement your work but stuck in some issues, so how long do you plan to release the official code?

**Comment by RameenAbdal** [comment]
We are currently working on the final version. Will be updated soon!

**Comment by milkcat0904** [comment]
okay，thx for reply!😃

**Comment by puppet101** [comment]
@RameenAbdal any update about the code? Thank you.

**Comment by ankur-pandey7** [comment]
@RameenAbdal did the team manage to decide on the publication of the code or we can still expect that more time is needed to publish this work?

**Comment by leonardodora** [comment]
@RameenAbdal 
the result seems perfect.
looking forwards to the release of the codes

**Comment by molo32** [comment]
amazing job, any news of when the code was released?
