### ISSUE TITLE
How to run this demo on the server?

### ISSUE THREAD

**Issue by puppet101** [RameenAbdal/StyleFlow#10]
Hi, thanks for your great work! 
How to run this GUI demo on the Linux server as it does not have desktop?  Thank you!

**Comment by RameenAbdal** [comment]
You could try VNC to display the GUI on a local machine with display. There might be other solutions too on the internet.

**Comment by puppet101** [comment]
Thank you! I have managed to run it on my Linux server.

**Comment by ZRJMoon** [comment]
> Thank you! I have managed to run it on my Linux server.

I have the same problem, too. And how do you solve it?

**Comment by zhywanna** [comment]
> > Thank you! I have managed to run it on my Linux server.
> 
> I have the same problem, too. And how do you solve it?

Did you solve that problem?
