### ISSUE TITLE
colab demo?

### ISSUE THREAD

**Issue by molo32** [RameenAbdal/StyleFlow#11]
can you add a demo colab.  thanks

**Comment by RameenAbdal** [comment]
Will try to include that in the next update.

**Comment by ak9250** [comment]
@RameenAbdal any update on this?

**Comment by RameenAbdal** [comment]
We are working on a Streamlit version right now. Should make things easier.

**Comment by ak9250** [comment]
@RameenAbdal great, I think a colab would also be helpful without a ui
