### ISSUE TITLE
Environment yaml for MacOS

### ISSUE THREAD

**Issue by bidHimArm** [RameenAbdal/StyleFlow#17]
Hi 

Same as for windows, `conda env create -f environment.yml` fails on macOS because of the Linux builds in the enironment.yml file.

![image](https://user-images.githubusercontent.com/36081903/103919635-8d7c6b00-5110-11eb-803f-b6c93b81f89a.png)

Maybe exporting the environment using `conda env export --from-history` will fix the problem and make it work cross platforms.

**Comment by johndpope** [comment]
you're not going to get anywhere on a mac - no cuda drivers / nvidia = no machine learning.

**Comment by bidHimArm** [comment]
Thanks !
