### ISSUE TITLE
No UI showing up (Windows 10)

### ISSUE THREAD

**Issue by polarfoxDev** [RameenAbdal/StyleFlow#21]
![image](https://user-images.githubusercontent.com/33626498/103928219-d128a200-511b-11eb-89f9-9966139a5019.png)
When launching `main.py` or `main_attribute.py`, I don't get any UI opening up and CLI stays in the state shown..

Using anaconda3 in Anaconda Prompt

Am I doing anything wrong or does anyone have an idea what I could try?

**Comment by polarfoxDev** [comment]
I just found out I'm actually having a problem similar to #13

**Comment by adityar224** [comment]
![image](https://user-images.githubusercontent.com/62930521/104131142-997b5d80-539a-11eb-9ba0-00fc81d0a310.png)
How Do I Resolve this?

**Comment by carlosedubarreto** [comment]
@adityar224 
I guess that you are probably missing some cuda toolkit driver.

Look at this page.
https://developer.nvidia.com/CUDA-toolkit-archive

I have donwloaded in my pc the 10.0 and 10.1 version. Sometimes i have to change from one to another...
Hope it helps

**Comment by adityar224** [comment]
> @adityar224
> I guess that you are probably missing some cuda toolkit driver.
> 
> Look at this page.
> https://developer.nvidia.com/CUDA-toolkit-archive
> 
> I have donwloaded in my pc the 10.0 and 10.1 version. Sometimes i have to change from one to another...
> Hope it helps

Can we run this program without a CUDA-capable gpu?

**Comment by justinjohn0306** [comment]
Nop
