### ISSUE TITLE
Not finding gpu

### ISSUE THREAD

**Issue by augustfr** [RameenAbdal/StyleFlow#44]
Not sure why i'm getting this error. I'm on a aws ec2 p2 instance with a nvidia tesla v100 gpu. I'm running python 3.6, and cuda 10.1. Any thoughts?

<img width="966" alt="Screen Shot 2021-01-18 at 6 18 18 PM" src="https://user-images.githubusercontent.com/68298953/104979668-b0810780-59b9-11eb-91b6-f7d22ebef2ba.png">

**Comment by chaowentao** [comment]
@augustfr CUDA 10.1 doesn't support tf 1.15. You can reinstall CUDA 10.0
