### ISSUE TITLE
Web UI version working on colab with minimal changes.

### ISSUE THREAD

**Issue by ashwath98** [RameenAbdal/StyleFlow#51]
Hey I managed to get the webui working on colab (using local tunnel) with really minimal changes (basically just some path changes in code)
The results I got were really amazing,

If you would like me to share the NB please let me know

**Comment by RameenAbdal** [comment]
Sure.

**Comment by ashwath98** [comment]
https://colab.research.google.com/gist/ashwath98/33cb2495c176c1fd2de44695ff479dc2/styleflowdemo.ipynb?pli=1#scrollTo=F5k0lCwNI6dG
