### ISSUE TITLE
Where is the Microsoft Face API ？

### ISSUE THREAD

**Issue by diaodeyi** [RameenAbdal/StyleFlow#55]
Hi, thank you for your amazing work!
the Microsoft Face API is mentioned in the paper, But in the code i do not find it.

**Comment by justinjohn0306** [comment]
[https://azure.microsoft.com/en-in/services/cognitive-services/face/#demo](url)

scroll down and till you find Face detection. Upload your photo, select Detection Model: detection_01

**Comment by justinjohn0306** [comment]
https://azure.microsoft.com/en-in/services/cognitive-services/face/#demo

scroll down the page and look for Face detection section, upload your image, select the detection Model: detection_01
