### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by dobrosketchkun** [RameenAbdal/StyleFlow#6]
Could you please say how long will it take to publish your code?
PS Is it possible to publish it with a google collab link?

**Comment by Radium98** [comment]
I want to know how long it takes to publish your code.

**Comment by 1moeses** [comment]
May you even publish your code? Or are there any restrictions on the part of Adobe?

**Comment by aertist** [comment]
Where's the code bruh? 💀

**Comment by harshitjawla** [comment]
Lool. Opensource but no code?. Wtf is this project.
You must have created this repo after uploading code.

**Comment by harshitjawla** [comment]
Who else is from 2 minute paper :)

**Comment by omril1** [comment]
I suspect I got scammed into getting here

**Comment by unknownue** [comment]
There are still code last night, but now all the code have gone.

**Comment by Brejlounek** [comment]
When is the code going to be available? :(((((((((

**Comment by MankaranSingh** [comment]
the way you guys are disrespecting the authors, they are better off not uploading it .. ..

**Comment by IDEKENTERPRISES** [comment]
Literally, they will be uploading the code soon so be patient. You didn't contribute to this paper in the slightest so you have no right to make the authors rush and feel bad.

**Comment by justinjohn0306** [comment]
Patience people. It'll be out when it will be out know what I'm saying? So
just relax.

**Comment by gitlabspy** [comment]
I made a tensorflow version of it (not sure 100% accurate or not but it works). All you need is plugin in your labels and w. https://github.com/gitlabspy/styleflow

**Comment by MankaranSingh** [comment]
> I made a tensorflow version of it (not sure 100% accurate or not but it works). All you need is plugin in your labels and w. https://github.com/gitlabspy/styleflow

dayumn, thanks for your contributions man. will love to contribute to it!

**Comment by MentalGear** [comment]
Oh no, the 10 minute sensation crowd has arrived. If I were the authors, I would purposely delay it now, so I won't have the issue ticker overflowing with requests from newbies on how "things don't work". Just give it a few days/weeks to weed out the crowd.

**Comment by Brejlounek** [comment]
> Oh no, the 10 minute sensation crowd has arrived. If I were the authors, I would purposely delay it now, so I won't have the issue ticker overflowing with requests from newbies on how "things don't work". Just give it a few days/weeks to weed out the crowd.

Of course you need to spit on these people, you are clearly better than them.

**Comment by MentalGear** [comment]
> > Oh no, the 10 minute sensation crowd has arrived. If I were the authors, I would purposely delay it now, so I won't have the issue ticker overflowing with requests from newbies on how "things don't work". Just give it a few days/weeks to weed out the crowd.
> 
> Of course you need to spit on these people, you are clearly better than them.

Not saying that, just stating the obvious facts.

**Comment by RameenAbdal** [comment]
Patience guys. Let's not make this unprofessional :). There is a protocol one needs to follow for publishing papers/code. The paper is in the reviewing stage (going through a review cycle) and we feel positive about it. I mentioned this in the previous issues as well.

**Comment by ivan2340** [comment]
> Patience guys. Let's not make this unprofessional :). There is a protocol one needs to follow for publishing papers/code. The paper is in the reviewing stage (going through a review cycle) and we feel positive about it. I mentioned this in the previous issues as well.

Thank you so much for not taking people's enthusiasm about those topics negatively! And Thank you for the reply! 👍

**Comment by RameenAbdal** [comment]
The UI code for the faster inference model (refer to the paper) has been updated.
