### ISSUE TITLE
Attribute Degree List

### ISSUE THREAD

**Issue by SURABHI-GUPTA** [RameenAbdal/StyleFlow#60]
@RameenAbdal can you elaborate on the role of degree of the specific attribute in code?

    attribute_names = ['Gender', 'Glasses', 'Yaw', 'Pitch', 'Baldness', 'Beard', 'Age', 'Expression']
    attr_degree_list = [1.5, 2.5, 1., 1., 2, 1.7, 0.93, 1.]

**Comment by RameenAbdal** [comment]
There are two reasons for the different scaling factors. First, the FFHQ dataset is not balanced, so the learned distribution has some unavoidable biases. e.g the glasses attribute would mainly be associated with old age etc. The sampled images from the StyleGAN and hence the dataset naturally has these biases. Secondly, the editing capability of an image depends on the distance from the mean face ( see https://arxiv.org/abs/2012.09036 ). For this reason, different projection/ embedding methods require different scales for editing real images. We have included this discussion in an updated version of the paper and will be online soon.
