### ISSUE TITLE
Generated Cars Dataset 

### ISSUE THREAD

**Issue by weilinie** [RameenAbdal/StyleFlow#62]
Very interesting work! It looks like only the generated Faces Dataset has been shared. May I ask if you could also share the generated Cars Dataset? Thanks!

**Comment by RameenAbdal** [comment]
The samples produced by LSUN-Car trained StyleGAN2 are not as good as faces. We found that during the preparation of the dataset, there are some random labels assigned by the classifiers which makes it less useful. We are working on high-quality labels.
