### ISSUE TITLE
About the network structure

### ISSUE THREAD

**Issue by jingjing-you** [RameenAbdal/StyleFlow#63]
Hi, the number of CNF is 4  in your paper ('we used 4 stacked CNF
functions') , but you only use one in your code ('cnf(512, '512-512-512-512-512', 17, 1)').  The performence of this kind is better?

**Comment by RameenAbdal** [comment]
This is the faster implementation version mentioned in the paper. The timing details are mentioned in the paper. The other model will be updated soon.
