### ISSUE TITLE
Train code please

### ISSUE THREAD

**Issue by diaodeyi** [RameenAbdal/StyleFlow#65]
Train code please

**Comment by RameenAbdal** [comment]
Will be updated.

**Comment by maciejwolczyk** [comment]
Hi! Do you have an estimate for when the code will be available?

**Comment by TKasperczyk** [comment]
If you could give us an approximate ETA, that would be great!

**Comment by vishnukool** [comment]
This is awesome work mate!
I've been dying to play around with this. Really looking forward to the training code to play around 🙏 
An approximate ETA would be great!

**Comment by vishnukool** [comment]
@RameenAbdal thanks for adding training code example. I think we can close this now unless you plan to add anything else?
