### ISSUE TITLE
Support for animals?

### ISSUE THREAD

**Issue by franz101** [RameenAbdal/StyleFlow#7]
Is it possible to grow a cat a beard or is it not possible due to the non-existence of cat moustaches in the dataset?

**Comment by MoffKalast** [comment]
Asking the real questions.

**Comment by RameenAbdal** [comment]
:P Well, you never know.

**Comment by GT135813** [comment]
> Is it possible to grow a cat a beard or is it not possible due to the non-existence of cat moustaches in the dataset?

To cat, or not to cat, that is the question.

**Comment by franz101** [comment]
Asking for science and my cat
