### ISSUE TITLE
What is the relationship between a0 and z0?

### ISSUE THREAD

**Issue by fungtion** [RameenAbdal/StyleFlow#75]
The a0 is introced as a condition when transforming between two domains, and it said this conditional mapping helps keep identity, where the identity keeped in, z0 or a0? Are they parallel for identity or complementate each other?

**Comment by RameenAbdal** [comment]
Ideally, it would be good to have an identity vector incorporated in a0 with the help of some high-quality face recognition frameworks. But here, we assume that multiple attributes encoded in (a0,z0) pair already encodes enough information which constraints the change in identity during an edit.
