### ISSUE TITLE
Adding Docker support

### ISSUE THREAD

**Issue by flavienbwk** [RameenAbdal/StyleFlow#8]
Hi,

Thanks for publishing the StyleFlow code and congratulations. That's massive work and I had no trouble installing the project. It works very well.

Would you be interested in adding Docker support to StyleFlow as an alternative install ?

Please find the PR below !

**Comment by carlosedubarreto** [comment]
Hello @flavienbwk can you share what system did you install?
I was trying on windows using Miniconda and on the first command it already didnt work for me. :(

Thanks for the attention

**Comment by flavienbwk** [comment]
Hi what do you try to install? The Docker version on my fork or the official install with anaconda and Python env?

**Comment by carlosedubarreto** [comment]
LOL sorry it was the anaconda and python env.
Butr I didnt noticed that the subject of this issue was about Docker... sorry for making this a mess 😅

**Comment by flavienbwk** [comment]
No worry ! :p

**Comment by johndpope** [comment]
this has dockerfile - 
https://github.com/NVlabs/stylegan2-ada

and fix here - though there's probably a january snapshot on the way.
https://github.com/NVlabs/stylegan2-ada/pull/51

**Comment by flavienbwk** [comment]
#9 closes this!

**Comment by johndpope** [comment]
you missed this Docker base image - 
it fixes 3090 issues.

nvcr.io/nvidia/tensorflow:20.12-tf1-py3

**Comment by flavienbwk** [comment]
The Tensorflow version of StyleFlow (1.15) was compiled against Cuda 10.0

**Comment by johndpope** [comment]
no. wasted 4-5 days resolving this.  https://github.com/NVlabs/stylegan2-ada/issues/32
