### ISSUE TITLE
different w_s doing forward and inverse transformation with conditional ffjord

### ISSUE THREAD

**Issue by imthebilliejoe** [RameenAbdal/StyleFlow#81]
Hi, I was able to train a version of styleflow in tf2, and I obtain good (but not good enough) results using 10k images of which i calculated (with external models) only two attributes: age and gender.

I train the model (styleflow) for 20 epoches with batch=64 but when I do forward and inverse (with the same attributes) the resulting w (and the image I obtain from it in Stylegan2) is slightly different while I was expecting to be exactly the same.

What do you think I'm still missing?

Some ideas:
Should I probably go for more epoches?
Should I go for more than 10k images?
are only 2 attributes not enough? (on the paper you wrote that using only one attribute would overfit the model)
On the paper you train for 10 epoches and batch of 5(!!!) but with this setting my model really seems to not converge (with my data).

**Comment by zhanghongyong123456** [comment]
Hello, Are you training yourself? I want to ask a question. Can I add more attributes directly in test mode?

**Comment by RameenAbdal** [comment]
Firstly, the flows are invertible so if you do not change anything, it is expected that the forward and inverse operations would not change anything. So, this part you might need to check carefully. One reason might be you are resampling the noise which slightly changes the high-frequency features.  2 attributes are probably not enough. No, you cannot add more attributes in the test mode.
