### ISSUE TITLE
How to use the UI?

### ISSUE THREAD

**Issue by Sentero-esp12** [RameenAbdal/StyleFlow#84]
When I run `python main.py` I see the UI with the blue dots: 
![image](https://user-images.githubusercontent.com/35060206/112962678-51750700-914f-11eb-89cf-21128d72e1c6.png)
When I click the buttons, nothings happens (unless I click the reload button [at the bottom], then the program crashes).
Should I install something else for it to work? 
I have Linux Mint 20 and gtx 750 ti.

P.S. Apparently one needs to click on the blue dots

**Comment by leeisack** [comment]
hi. how to solve that?

**Comment by Sentero-esp12** [comment]
I clicked blue dots
