### ISSUE TITLE
Windows 10

### ISSUE THREAD

**Issue by codeleger** [RameenAbdal/StyleFlow#87]
Following the Win 10 fork --> https://github.com/justinjohn0306/StyleFlow-Windows-10

Inside the mentioned styleflow environment.

> conda env create -f env_windows.yml (Download and Install Anaconda): [Download Anaconda 64-Bit Graphical Installer] (https://www.anaconda.com/products/individual)
conda activate styleflow
conda install pytorch==1.2.0 torchvision==0.4.0 cudatoolkit=10.0 -c pytorch [Also available here:(https://pytorch.org/get-started/previous-versions/)]
>...
>... adapted custom_ops.py ... compiler_bindir_search_path = [
    'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64',
]

@justinjohn0306 
If I want to execute the main.py I get an error with CV2.

Can anyone provide hints how to solve it? 
I am not a python guy, can I track down which DLL is missing?

I've added also added path to:
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64

Error while execution:
>python main.py
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    from ui.ui import Ui_Form
  File "C:\Users\<User>\Downloads\StyleFlow\ui\ui.py", line 10, in <module>
    from ui.mouse_event import ReferenceDialog
  File "C:\Users\<User>\Downloads\StyleFlow\ui\mouse_event.py", line 5, in <module>
    import cv2
  File "C:\Users\<User>\anaconda3\envs\styleflow\lib\site-packages\cv2\__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.`

Last message is about: The mentioned module was not found

Support would be appreciated! Thanks

**Comment by dodu3112** [comment]
OS: Microsoft Windows 10 Home N
Version: 10.0.19042 Build 19042

**Comment by codeleger** [comment]
See issue above.
